Filter:
  ros__parameters:
    use_sim_time: false #has effect on this->now() time in a ros2 node if its true you need to run gazebo for the time counter to go up
    odom_frame: "odom"
    base_link_frame: "base_link"
    publish_tf: false
    rate: 50.0
    model_type: 1 # CONSTANT_HEADING_RATE:0   CAR:1
    # model_plugin: "model::Model"
    model_plugin: ""
    filter_type: 0 # EKF:0 UKF:1
    use_cmd: false # I'm only using it to set linear x to zero when the robot is stationary (for imu only case)
    states: [''] 
    initial_states: [0.0,0.0,0.0,  # x,y,z
                     0.0,0.0,0.0,  # roll,pitch,yaw
                     0.0,0.0,0.0,  # x_dot,y_dot,z_dot
                     0.0,0.0,0.0,  # roll_dot,pitch_dot,yaw_dot
                     0.0,0.0,0.0,] # x_ddot,y_ddot,z_ddot

    Q: [      0.05 , 0.0  , 0.0  , 0.0  , 0.0  ,0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.05 , 0.0  , 0.0  , 0.0  ,0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.05 , 0.0  , 0.0  ,0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.05 , 0.0  ,0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.0  , 0.05 ,0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,0.05 , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,0.0  , 0.05 , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,0.0  , 0.0  , 0.05 , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,0.0  , 0.0  , 0.0  , 0.05 , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,0.0  , 0.0  , 0.0  , 0.0  , 0.05 , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.05 , 0.0  , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.05 , 0.0  , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.05 , 0.0  , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.05 , 0.0  ,
              0.0  , 0.0  , 0.0  , 0.0  , 0.0  ,0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.05  ,]

           
    R: [      4.0e-8 , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
              0.0    , 4.0e-8 , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
              0.0    , 0.0    , 4.0e-8 , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
              0.0    , 0.0    , 0.0    , 4.0e-8 , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
              0.0    , 0.0    , 0.0    , 0.0    , 4.0e-8 ,0.0    , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
              0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,4.0e-8 , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
              0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 4.0e-8 , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
              0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 4.0e-8 , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
              0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 4.0e-8 , 0.0  , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
              0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 4.0e-8 , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
              0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0  , 4.0e-8 , 0.0    , 0.0    , 0.0    , 0.0  ,
              0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0  , 0.0    , 4.0e-8 , 0.0    , 0.0    , 0.0  ,
              0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0  , 0.0    , 0.0    , 4.0e-8 , 0.0    , 0.0  ,
              0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0  , 0.0    , 0.0    , 0.0    , 4.0e-8 , 0.0  ,
              0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0  , 0.0    , 0.0    , 0.0    , 0.0    , 4.0e-8 ,]
  
    # R: [      4.0e+4 , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 4.0e+4 , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 4.0e+4 , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 4.0e+4 , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 0.0    , 4.0e+4 ,0.0    , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,4.0e+4 , 0.0    , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 4.0e+4 , 0.0    , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 4.0e+4 , 0.0  , 0.0    , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 4.0e+4 , 0.0  , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 4.0e+4 , 0.0  , 0.0    , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0  , 4.0e+4 , 0.0    , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0  , 0.0    , 4.0e+4 , 0.0    , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0  , 0.0    , 0.0    , 4.0e+4 , 0.0    , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0  , 0.0    , 0.0    , 0.0    , 4.0e+4 , 0.0  ,
    #           0.0    , 0.0    , 0.0    , 0.0    , 0.0    ,0.0    , 0.0    , 0.0    , 0.0  , 0.0  , 0.0    , 0.0    , 0.0    , 0.0    , 4.0e+4 ,]
  

    # sensor_0_topic: "imu0"
    # sensor_0_states: ["yaw_dot"]
    # sensor_0_msg: "sensor_msgs::msg::Imu"
    # sensor_1_topic: "imu1"
    # sensor_1_states: ["yaw_dot" ]
    # sensor_1_msg: "sensor_msgs::msg::Imu"
    # sensor_2_topic: "odom" 
    # sensor_2_states: ["x_dot"]
    # sensor_2_msg: "nav_msgs::msg::Odom"


    sensor_0_topic: "/ardrone/imu"
    sensor_0_states: ["roll" , "pitch" ,"yaw" ]
    sensor_0_msg: "sensor_msgs::msg::Imu"
    sensor_1_topic: "/ardrone/odometry/raw" 
    sensor_1_states: ["z" , "x_dot" , "y_dot" ]
    sensor_1_msg: "nav_msgs::msg::Odom"


    #what if we also needed a measurement model like for lidar which doesn't see the states directly and we need linearization --> future work