Filter:
  ros__parameters:
    use_sim_time: true
    test: "hi"
    model_type: 0 # CONSTANT_HEADING_RATE:0   CAR:1
    filter_type: 0 # EKF:0 UKF:1
    states: ["x" , "y" , "yaw" , "x_dot" , "yaw_dot" , "x_ddot"] 
    sensor_0_topic: "imu"
    sensor_0_states: ["yaw_dot" , "x_ddot"]
    sensor_1_topic: "odom"
    sensor_1_states: ["x" , "y" , "yaw"]

    #what if we also needed a measurement model like for lidar which doesn't see the states directly and we need linearization --> future work